# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

TUMBLR_KEY: v35llhhxuXCAJDpCe9Dv8raaR8KB1owCYfPA8i909BfkXbvB6y
TUMBLR_SECRET: BgaN757R1qoevRHarxWI8usQekgEoT6mAypN7EZJdvJ5Z81TRW
TUMBLR_OAUTH_ACCESS_TOKEN: LeDgz9IYwofUuVGT1jyXgV6LWMjqFDHFQmZfy1aWIqqgGazAja
TUMBLR_OAUTH_SECRET_TOKEN: ILJEI1f01ufpodfWwL4rRoafFTI0tWNQDlqrWvek2xtd835HNb
