# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


TUMBLR_KEY: FF6R2u0KgDdSATT3pTub0WPmaUVYZKSTsoRZTk9Sm4Yxm7tsVd
TUMBLR_SECRET: xiEosXVnGK8fcITmKUtJ5AadJ4kkFXKUBRSQ5RZVdCawOFRKOm
TUMBLR_OAUTH_ACCESS_TOKEN: G9T9JsX5c7lQ0LWOzETOAUvX50kRFKptFgXTm488tzZqfAy6LT
TUMBLR_OAUTH_SECRET_TOKEN: MyZrKkG9QTFbIogySQfpXDvoCTQcBYhht5LiYORL9z1oU1o6wJ

TWITTER_CONSUMER_KEY: u91h4BZ7PJfaHh2WaFw
TWITTER_CONSUMER_SECRET: Yov9eg0JNpB42g7ILcwCGnE8LQNbzsVyDzA8F9ozFSY
TWITTER_ACCESS_TOKEN: 2306963983-BeQl2N4sVfzEmNbl3xnnKsOtEvvTzRxZqTy9NGb
TWITTER_ACCESS_TOKEN_SECRET: FJc39IkNKfdYtQbt6KyeLQtAL8NKiImFbnStv8WIgsK8Y

