# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

TWITTER_CONSUMER_KEY: G3rtTvc7YnBpXMbukyUguQ
TWITTER_CONSUMER_SECRET: kg5ZykIfC0kx1tHbNEKw4gJbPEnJhSwPfN4rz4a8VU
TWITTER_ACCESS_TOKEN: 2306963983-BeQl2N4sVfzEmNbl3xnnKsOtEvvTzRxZqTy9NGb
TWITTER_ACCESS_TOKEN_SECRET: FJc39IkNKfdYtQbt6KyeLQtAL8NKiImFbnStv8WIgsK8Y